import type { AnnotationPin, AnnotationScreen } from "@/types";

export const ANNOTATIONS_COPY = {
  toggleHint: "Numbered pins explain design choices on this screen.",
  closeHint: "Press Esc to close the note.",
  close: "Close",
  pinLabel: (n: number) => `Annotation ${n}`,
  decisionLabel: "Design decision",
  problemLabel: "User problem",
  metricLabel: "Metric it moves",
  metricKindLabel: {
    input: "Input",
    output: "Output",
    check: "Check",
  },
} as const;

export const ANNOTATIONS: Record<AnnotationScreen, readonly AnnotationPin[]> = {
  alerts: [
    {
      id: "alerts-severity",
      screen: "alerts",
      targetId: "annotate-severity-summary",
      number: 1,
      decision: "Severity counts are compact filter pills, not large stat cards.",
      problem: "Big KPI cards steal attention from the queue an engineer must work.",
      metricKind: "output",
      metric: "Mean time to resolve (MTTR)",
    },
    {
      id: "alerts-filters",
      screen: "alerts",
      targetId: "annotate-filter-bar",
      number: 2,
      decision: "Filters live in the URL and show as removable chips.",
      problem: "Shared views break when filters are only local component state.",
      metricKind: "input",
      metric: "% of alerts opened in the workspace",
    },
    {
      id: "alerts-guided",
      screen: "alerts",
      targetId: "annotate-alerts-table",
      number: 3,
      decision: "Scenario rows show a Guided badge only when Guide is on.",
      problem: "New L1 engineers cannot tell which cases teach the TAC method.",
      metricKind: "input",
      metric: "% of alerts opened in the workspace",
    },
    {
      id: "alerts-severity-cell",
      screen: "alerts",
      targetId: "annotate-alerts-table",
      number: 4,
      decision: "Severity always pairs an icon with a label, never color alone.",
      problem: "Color-only severity fails accessibility and slows scanning under stress.",
      metricKind: "check",
      metric: "False-negative escalations found later",
    },
    {
      id: "alerts-actions",
      screen: "alerts",
      targetId: "annotate-alerts-table",
      number: 5,
      decision: "Row hover reveals Assign to me and Mark false positive.",
      problem: "Common queue actions should not require opening a full investigation.",
      metricKind: "output",
      metric: "% alerts closed at L2 without escalation",
    },
    {
      id: "alerts-time",
      screen: "alerts",
      targetId: "annotate-alerts-table",
      number: 6,
      decision: "First seen is relative, with absolute time on hover in the active timezone.",
      problem: "Absolute-only timestamps force mental math during an 8 hour shift.",
      metricKind: "output",
      metric: "Median time to first evidence",
    },
  ],
  investigate: [
    {
      id: "inv-rail",
      screen: "investigate",
      targetId: "guide-step-rail",
      number: 1,
      decision: "A narrow step rail encodes Scope, Logs, Console, Resolve.",
      problem: "Without a method, L1 hops tools and loses the incident thread.",
      metricKind: "output",
      metric: "Mean time to resolve (MTTR)",
    },
    {
      id: "inv-time",
      screen: "investigate",
      targetId: "guide-time-scope",
      number: 2,
      decision: "Time scope is first. Logs and console inherit the window.",
      problem: "Re-scoping each tool to the incident is the biggest daily time sink.",
      metricKind: "input",
      metric: "% with a pinned time window",
    },
    {
      id: "inv-timeline",
      screen: "investigate",
      targetId: "guide-timeline",
      number: 3,
      decision: "A correlated timeline shows dots per log type across the window.",
      problem: "Beacon and retry patterns stay hidden in flat tables.",
      metricKind: "output",
      metric: "Median time to first evidence",
    },
    {
      id: "inv-tabs",
      screen: "investigate",
      targetId: "guide-log-tabs",
      number: 4,
      decision: "Traffic, Threat, URL, Decryption, System, and Config stay in one workspace.",
      problem: "Tab hopping across products drops context and burns shift time.",
      metricKind: "input",
      metric: "% of alerts opened in the workspace",
    },
    {
      id: "inv-query",
      screen: "investigate",
      targetId: "guide-query-bar",
      number: 5,
      decision: "The query bar uses PAN-OS style fields with inline validation.",
      problem: "Engineers already think in these fields. A foreign query language slows first evidence.",
      metricKind: "output",
      metric: "Median time to first evidence",
    },
    {
      id: "inv-evidence",
      screen: "investigate",
      targetId: "guide-evidence",
      number: 6,
      decision: "Pinned evidence is a first-class tray that flows into resolution.",
      problem: "Escalation and closure often force re-collection of the same rows.",
      metricKind: "output",
      metric: "% alerts closed at L2 without escalation",
    },
    {
      id: "inv-console",
      screen: "investigate",
      targetId: "guide-console",
      number: 7,
      decision: "Diagnostics stay in a resizable console on the same screen.",
      problem: "Leaving the workspace for CLI resets context right before a risky change.",
      metricKind: "input",
      metric: "Console usage per investigation",
    },
  ],
  resolve: [
    {
      id: "res-root",
      screen: "resolve",
      targetId: "guide-root-cause",
      number: 1,
      decision: "Root cause types include true threat and false positive beside fix paths.",
      problem: "UIs that only offer fix push engineers to close the wrong class of alert.",
      metricKind: "check",
      metric: "False-negative escalations found later",
    },
    {
      id: "res-outcome",
      screen: "resolve",
      targetId: "guide-outcome",
      number: 2,
      decision: "The middle panel switches among policy fix, config fix, and escalation package.",
      problem: "One generic close form hides the action the case actually needs.",
      metricKind: "output",
      metric: "% alerts closed at L2 without escalation",
    },
    {
      id: "res-evidence",
      screen: "resolve",
      targetId: "guide-resolve-evidence",
      number: 3,
      decision: "Pinned evidence from investigation appears here unchanged.",
      problem: "Handoffs fail when the trail lives only in the investigator's scratch notes.",
      metricKind: "output",
      metric: "Mean time to resolve (MTTR)",
    },
    {
      id: "res-verify",
      screen: "resolve",
      targetId: "guide-verify",
      number: 4,
      decision: "Verify is a required gate on fix paths before Resolve is enabled.",
      problem: "Closing without proof creates reopen churn and missed threats.",
      metricKind: "check",
      metric: "Verify-gate bypass attempts",
    },
    {
      id: "res-closure",
      screen: "resolve",
      targetId: "guide-closure",
      number: 5,
      decision: "Closure notes are pre-drafted from evidence and stay editable.",
      problem: "Empty ticket notes make the next shift replay the whole investigation.",
      metricKind: "check",
      metric: "Reopen rate within 7 days",
    },
    {
      id: "res-footer",
      screen: "resolve",
      targetId: "guide-resolve-footer",
      number: 6,
      decision: "Disabled Resolve or Escalate states explain exactly what is missing.",
      problem: "A silent disabled button stalls L2 without teaching the gate.",
      metricKind: "check",
      metric: "Verify-gate bypass attempts",
    },
  ],
};

export function annotationsFor(screen: AnnotationScreen | null): readonly AnnotationPin[] {
  if (!screen) return [];
  return ANNOTATIONS[screen];
}
