import type { GuideStep, ScenarioId, StepId } from "@/types";

export const GUIDE_COPY = {
  next: "Next",
  back: "Back",
  skip: "Skip",
  doItForMe: "Do it for me",
  progress: (current: number, total: number) => `Step ${current} of ${total}`,
  closeHint: "Press Esc to exit Guide. Progress is saved.",
  targetMissing: "This control is on another screen. Use Do it for me to jump there.",
  completeTitle: "Guide complete",
  completeBody: "You finished the guided path for this case. Turn Guide off any time from the top bar.",
} as const;

export const GUIDE_STEPS: Record<ScenarioId, readonly GuideStep[]> = {
  A: [
    {
      id: "a-scope",
      targetId: "guide-time-scope",
      title: "Pin the incident window",
      body: "The user said around 2:20 PM. Set the window first. TAC starts every case by scoping time so every log and command stays on the same incident.",
      actionId: "confirm-window",
      railStep: "scope",
      markDone: "scope",
      pathPrefix: "/investigate/",
    },
    {
      id: "a-traffic",
      targetId: "guide-log-tabs",
      title: "Read the traffic end reason",
      body: "Open the Traffic tab. Look for session end reason decrypt-error with very low bytes received. That tells you the allow rule fired but the session still failed.",
      actionId: "set-tab-traffic",
      railStep: "logs",
      pathPrefix: "/investigate/",
    },
    {
      id: "a-decrypt",
      targetId: "guide-log-tabs",
      title: "Check decryption next",
      body: "Switch to Decryption. Find Certificate pinned on Decrypt-All-Outbound. TAC confirms decrypt failure before blaming URL filtering or the security rule.",
      actionId: "set-tab-decryption",
      railStep: "logs",
      pathPrefix: "/investigate/",
    },
    {
      id: "a-url",
      targetId: "guide-log-tabs",
      title: "Rule out URL filtering",
      body: "Open the URL tab. Category business-and-economy with allow means URL policy is not the blocker. This is the deliberate red herring check.",
      actionId: "set-tab-url",
      railStep: "logs",
      pathPrefix: "/investigate/",
    },
    {
      id: "a-pin",
      targetId: "guide-evidence",
      title: "Pin what you will defend",
      body: "Pin the decrypt-error traffic row and the certificate pinned decryption row. Evidence must travel with you into resolution so you do not re-collect later.",
      actionId: "pin-scenario-a-logs",
      railStep: "logs",
      markDone: "logs",
      pathPrefix: "/investigate/",
    },
    {
      id: "a-console",
      targetId: "guide-console",
      title: "Verify in the console",
      body: "Open the console and run the decryption policy match for this flow. TAC verifies the active decrypt hit before staging a no-decrypt exclusion.",
      actionId: "run-decrypt-match-a",
      railStep: "console",
      markDone: "console",
      pathPrefix: "/investigate/",
    },
    {
      id: "a-resolve-nav",
      targetId: "guide-resolve-actions",
      title: "Move to resolution",
      body: "Open Resolve when the trail is clear. Keep the pinned evidence. The outcome screen is where you stage the exclusion and prove it.",
      actionId: "go-resolve",
      railStep: "resolve",
      pathPrefix: "/investigate/",
    },
    {
      id: "a-root-cause",
      targetId: "guide-root-cause",
      title: "Name the root cause",
      body: "Choose Misconfiguration. Salesforce pins its certificate, so decrypt breaks the handshake. A clear cause type keeps L2 honest about what changed.",
      actionId: "set-root-misconfiguration",
      railStep: "resolve",
      pathPrefix: "/resolve/",
    },
    {
      id: "a-stage",
      targetId: "guide-outcome",
      title: "Stage the no-decrypt rule",
      body: "Stage No-Decrypt-Pinned-SaaS above Decrypt-All-Outbound. Policy position matters. TAC stages before closing so verify can prove the new match.",
      actionId: "stage-policy-a",
      railStep: "resolve",
      pathPrefix: "/resolve/",
    },
    {
      id: "a-verify",
      targetId: "guide-verify",
      title: "Verify, then resolve",
      body: "Run verify. It should match the no-decrypt rule. Only then resolve the alert. The gate stops a close without proof.",
      actionId: "run-verify",
      railStep: "resolve",
      markDone: "resolve",
      pathPrefix: "/resolve/",
    },
  ],
  B: [
    {
      id: "b-scope",
      targetId: "guide-time-scope",
      title: "Scope around the outage",
      body: "The tunnel dropped at 11:42 IST after a change window. Set the window first so system and config logs line up with CHG-4471.",
      actionId: "confirm-window",
      railStep: "scope",
      markDone: "scope",
      pathPrefix: "/investigate/",
    },
    {
      id: "b-system",
      targetId: "guide-log-tabs",
      title: "Read the system failure",
      body: "Open System logs. NO_PROPOSAL_CHOSEN on the child SA means Phase 2 failed. Phase 1 can still look healthy.",
      actionId: "set-tab-system",
      railStep: "logs",
      pathPrefix: "/investigate/",
    },
    {
      id: "b-config",
      targetId: "guide-log-tabs",
      title: "Find the config drift",
      body: "Open Config logs. Look for the PFS group change on ipsec-prisma during the change window. Drift after change is a common tunnel outage cause.",
      actionId: "set-tab-config",
      railStep: "logs",
      pathPrefix: "/investigate/",
    },
    {
      id: "b-pin",
      targetId: "guide-evidence",
      title: "Pin the trail",
      body: "Pin the NO_PROPOSAL_CHOSEN system log and the PFS config change. You will need both in the config diff and the closure note.",
      actionId: "pin-scenario-b-logs",
      railStep: "logs",
      markDone: "logs",
      pathPrefix: "/investigate/",
    },
    {
      id: "b-console",
      targetId: "guide-console",
      title: "Confirm IKE versus IPsec",
      body: "In the branch CLI, show the IKE SA and the IPsec SA. IKE up with IPsec missing proves Phase 2 mismatch before you touch config.",
      actionId: "run-vpn-check-b",
      railStep: "console",
      markDone: "console",
      pathPrefix: "/investigate/",
    },
    {
      id: "b-resolve-nav",
      targetId: "guide-resolve-actions",
      title: "Open resolution",
      body: "Go to Resolve with evidence pinned. This case is config drift, not a security rule change.",
      actionId: "go-resolve",
      railStep: "resolve",
      pathPrefix: "/investigate/",
    },
    {
      id: "b-root-cause",
      targetId: "guide-root-cause",
      title: "Call it config drift",
      body: "Select Config drift and note CHG-4471. Naming drift keeps the ticket honest and points to change process follow-up.",
      actionId: "set-root-config-drift",
      railStep: "resolve",
      pathPrefix: "/resolve/",
    },
    {
      id: "b-apply",
      targetId: "guide-outcome",
      title: "Revert PFS and verify",
      body: "Apply the revert to group14 on pune-fw-01, then run verify. Close only when the IPsec SA comes back.",
      actionId: "apply-config-b",
      railStep: "resolve",
      markDone: "resolve",
      pathPrefix: "/resolve/",
    },
  ],
  C: [
    {
      id: "c-scope",
      targetId: "guide-time-scope",
      title: "Scope the beacon window",
      body: "First beacon was about 09:12 IST. Set the window first so the 60 second pattern is visible on the timeline.",
      actionId: "confirm-window",
      railStep: "scope",
      markDone: "scope",
      pathPrefix: "/investigate/",
    },
    {
      id: "c-timeline",
      targetId: "guide-timeline",
      title: "See the beacon pattern",
      body: "Read the timeline strip. Regular dots every minute are a callback pattern, not a one-off allow miss.",
      railStep: "logs",
      pathPrefix: "/investigate/",
    },
    {
      id: "c-threat",
      targetId: "guide-log-tabs",
      title: "Open threat evidence",
      body: "Switch to Threat. Confirm Generic C2 beacon and the earlier malicious file. This is a true compromise path.",
      actionId: "set-tab-threat",
      railStep: "logs",
      pathPrefix: "/investigate/",
    },
    {
      id: "c-pin",
      targetId: "guide-evidence",
      title: "Pin IOCs for IR",
      body: "Pin the C2 threat rows you will put in the escalation package. Do not try to invent a policy fix for malware.",
      actionId: "pin-scenario-c-logs",
      railStep: "logs",
      markDone: "logs",
      pathPrefix: "/investigate/",
    },
    {
      id: "c-console",
      targetId: "guide-console",
      title: "Sanity check in console",
      body: "Run a threat log view for the host. TAC still verifies in CLI so the package matches what the device saw.",
      actionId: "run-threat-c",
      railStep: "console",
      markDone: "console",
      pathPrefix: "/investigate/",
    },
    {
      id: "c-resolve-nav",
      targetId: "guide-resolve-actions",
      title: "Escalate, do not fake a fix",
      body: "Open Resolve. The honest outcome is containment plus IR escalation, not a rule tweak.",
      actionId: "go-resolve",
      railStep: "resolve",
      pathPrefix: "/investigate/",
    },
    {
      id: "c-root-cause",
      targetId: "guide-root-cause",
      title: "Mark true threat",
      body: "Select True threat. Making escalate as easy as fix is the product rule for this case.",
      actionId: "set-root-true-threat",
      railStep: "resolve",
      pathPrefix: "/resolve/",
    },
    {
      id: "c-package",
      targetId: "guide-outcome",
      title: "Contain and package",
      body: "Tag the host into quarantine, then copy or download the escalation package. Escalate only when the package is ready.",
      actionId: "prepare-escalation-c",
      railStep: "resolve",
      markDone: "resolve",
      pathPrefix: "/resolve/",
    },
  ],
};

export function guideStepsFor(scenario: ScenarioId | null): readonly GuideStep[] {
  if (!scenario) return [];
  return GUIDE_STEPS[scenario];
}

export function railStepForGuideIndex(
  scenario: ScenarioId | null,
  index: number,
): StepId | undefined {
  const steps = guideStepsFor(scenario);
  return steps[index]?.railStep;
}
