/** Copy for log explorer, evidence, compare, reproduce. No em or en dashes. */

export const logsCopy = {
  pageTitle: "Logs",
  pageSubtitle: "Traffic and related logs for Acme Corp. Last 24 hours before demo clock.",
  allTypes: "All",
  queryPlaceholder: "( addr.src in 10.20.31.44 ) and ( port.dst geq 19302 )",
  queryHint: "PAN-OS style query. Fields and operators autocomplete.",
  emptyTitle: "No logs match",
  emptyBody: "Widen the time window or clear the query.",
  loading: "Loading logs…",
  errorTitle: "Could not filter logs",
  columns: "Columns",
  density: "Density",
  densityComfortable: "Comfortable",
  densityCompact: "Compact",
  pin: "Pin",
  filterBy: "Filter by",
  exclude: "Exclude",
  copy: "Copy",
  detailTitle: "Log detail",
  closeDetail: "Close detail",
  savedQueries: "Saved queries",
  saveQuery: "Save query",
  saveQueryDisabled: "Enter a valid query first",
  noSavedQueries: "No saved queries yet.",
  presetsLabel: "Window",
  preset1h: "Last 1h",
  preset4h: "Last 4h",
  preset24h: "Last 24h",
  presetScope: "Scope window",
  histogramLabel: "Event volume",
  configStripTitle: "Config changes in this window",
  configStripEmpty: "No config changes in the selected window.",
  configStripLink: "Open in Config audit",
  evidenceTitle: "Evidence",
  evidenceHint: "Explorer pre-scoped from Scope (failing user and time window).",
  evidenceContinue: "Continue to Compare",
  evidenceContinueHint: "Pin a useful row, then continue.",
  compareTitle: "Compare",
  compareHint: "Failing side vs working side. Differences are highlighted.",
  comparePin: "Pin comparison",
  comparePinned: "Comparison pinned",
  compareContinue: "Continue to Reproduce",
  compareFailing: "Failing",
  compareWorking: "Working",
  compareDiffTitle: "Diff",
  reproduceTitle: "Reproduce",
  reproduceHint: "Ask the customer to retry while watching logs live.",
  reproduceAsk: "Ask customer to retry now",
  reproduceAsked: "Retry requested. Watching live…",
  reproduceLive: "Live",
  reproduceStreamTitle: "Live traffic",
  reproducePcapTitle: "Packet capture",
  reproduceStartPcap: "Start packet capture",
  reproducePcapRunning: "Capture running",
  reproducePin: "Pin capture",
  reproducePinned: "Capture pinned",
  reproduceContinueHint: "Ask for a retry to capture live drops, then pin if useful.",
  fieldTime: "Time",
  fieldType: "Type",
  fieldSrc: "Source",
  fieldDst: "Destination",
  fieldUser: "User",
  fieldApp: "App",
  fieldRule: "Rule",
  fieldAction: "Action",
  fieldPort: "Port",
  fieldProto: "Proto",
  fieldZone: "Zone",
  fieldContainer: "Container",
  fieldLocation: "Location",
  fieldBytes: "Bytes",
} as const;
