/** Copy for Phase 8 supporting pages. No em or en dashes. */

export const policiesCopy = {
  title: "Policies",
  subtitle: "Security and decryption rules across Prisma Access containers",
  seeded: "security rules",
  tabSecurity: "Security",
  tabDecryption: "Decryption",
  searchPlaceholder: "Search by rule name, app, or service",
  filterContainer: "Container",
  filterAction: "Action",
  filterAll: "All",
  colPosition: "Pos",
  colName: "Name",
  colSource: "Source",
  colUser: "User",
  colDest: "Destination",
  colApp: "App",
  colService: "Service",
  colAction: "Action",
  colHits: "Hit count",
  colLastHit: "Last hit",
  colModified: "Modified by",
  drawerTitle: "Rule detail",
  drawerHistory: "Change history",
  drawerObjects: "Referenced objects",
  drawerLogs: "View matching logs",
  drawerConfig: "Open related changes",
  drawerClose: "Close rule detail",
  emptyTitle: "No rules match",
  emptyBody: "Clear filters or try a different search.",
  clearFilters: "Clear filters",
  loading: "Loading policies…",
  errorTitle: "Policies could not load",
  errorBody: "Something went wrong while reading the policy table.",
  retry: "Retry",
  disabled: "Disabled",
} as const;

export const objectsCopy = {
  title: "Objects",
  subtitle: "Address, service, and application objects used by policy",
  seeded: "objects",
  tabAddress: "Address",
  tabAddressGroups: "Address groups",
  tabServices: "Services",
  tabAppGroups: "Application groups",
  searchPlaceholder: "Search by name or value",
  filterContainer: "Container",
  filterAll: "All",
  colName: "Name",
  colType: "Type",
  colValue: "Value",
  colContainer: "Container",
  colWhereUsed: "Where used",
  unused: "Not referenced",
  drawerTitle: "Object detail",
  drawerClose: "Close object detail",
  drawerRules: "Used by rules",
  drawerOpenRule: "Open rule",
  emptyTitle: "No objects match",
  emptyBody: "Clear filters or try a different search.",
  clearFilters: "Clear filters",
  loading: "Loading objects…",
  errorTitle: "Objects could not load",
  errorBody: "Something went wrong while reading the object catalog.",
  retry: "Retry",
} as const;

export const remoteNetworksCopy = {
  title: "Remote networks",
  subtitle: "Branch IPsec tunnels into Prisma Access",
  seeded: "sites",
  searchPlaceholder: "Search by site, peer IP, or location",
  filterStatus: "Status",
  filterLocation: "Location",
  filterAll: "All",
  statusUp: "Up",
  statusDown: "Down",
  colName: "Site",
  colStatus: "Status",
  colPeer: "Peer IP",
  colLocation: "Location",
  colBandwidth: "Bandwidth",
  colUptime: "30d uptime",
  colChanged: "Last change",
  drawerTitle: "Tunnel detail",
  drawerClose: "Close tunnel detail",
  drawerHistory: "Tunnel history",
  drawerProfile: "IKE and IPsec profile",
  drawerLogs: "View site logs",
  drawerConfig: "Related config changes",
  emptyTitle: "No remote networks match",
  emptyBody: "Clear filters or try a different search.",
  clearFilters: "Clear filters",
  loading: "Loading remote networks…",
  errorTitle: "Remote networks could not load",
  errorBody: "Something went wrong while reading tunnel status.",
  retry: "Retry",
} as const;

export const mobileUsersCopy = {
  title: "Mobile users",
  subtitle: "GlobalProtect users currently connected",
  seeded: "connected users",
  searchPlaceholder: "Search by user, email, IP, or gateway",
  filterGateway: "Gateway",
  filterOs: "OS",
  filterAll: "All",
  colUser: "User",
  colEmail: "Email",
  colPrivateIp: "Private IP",
  colPublicIp: "Public IP",
  colLocation: "Location",
  colGateway: "Gateway",
  colOs: "OS",
  colVersion: "GP version",
  colSince: "Connected since",
  emptyTitle: "No mobile users match",
  emptyBody: "Clear filters or try a different search.",
  clearFilters: "Clear filters",
  loading: "Loading mobile users…",
  errorTitle: "Mobile users could not load",
  errorBody: "Something went wrong while reading the user list.",
  retry: "Retry",
  openLogs: "View user logs",
} as const;

export const configAuditCopy = {
  title: "Config audit",
  subtitle: "Who changed what, with before and after",
  seeded: "config changes",
  searchPlaceholder: "Search by change ID, admin, path, or summary",
  filterWindow: "Window",
  filterContainer: "Container",
  filterAll: "All",
  window24h: "Last 24 hours",
  windowAll: "All time",
  colWhen: "When",
  colChange: "Change",
  colAdmin: "Admin",
  colContainer: "Container",
  colSummary: "Summary",
  drawerTitle: "Change detail",
  drawerClose: "Close change detail",
  before: "Before",
  after: "After",
  relatedRule: "Related rule",
  relatedObject: "Related object",
  relatedTicket: "Related ticket",
  openLogs: "View config logs",
  emptyTitle: "No config changes match",
  emptyBody: "Clear filters or try a different search.",
  clearFilters: "Clear filters",
  loading: "Loading config audit…",
  errorTitle: "Config audit could not load",
  errorBody: "Something went wrong while reading change history.",
  retry: "Retry",
} as const;

export const briefCopy = {
  title: "Brief",
  subtitle: "Problem, persona, playbook, and how to review this demo",
  problemTitle: "Problem",
  problem:
    "A customer reports Google Meet is not working, or the platform raises a branch tunnel down alert. The engineer must turn a vague complaint into a precise scope (who, when, what changed), find evidence across logs, config history, and CLI, prove the root cause, get the fix approved, verify with the customer, and document it. Today that context lives in 5 to 7 different tools, so time to root cause is slow and evidence is lost.",
  personaTitle: "Persona",
  personaName: "Priya Nair, Cloud Security TAC Engineer (L2)",
  personaBullets: [
    "Works customer cases on a Prisma Access style SASE platform: mobile users on GlobalProtect, branches on IPsec remote networks.",
    "Holds 6 to 10 active tickets. P1 SLA is 1 hour to first response.",
    "Method: never trust the first description. Scope first, then logs, then compare a working user with a failing one, then reproduce live, then prove it in the CLI.",
    "Never changes customer config without written approval.",
    "Success: correct root cause on the first attempt, customer confirms the fix, clean RCA.",
  ],
  playbookTitle: "TAC playbook",
  playbookSteps: [
    "Intake. Read the ticket. Check priority, SLA, customer, product, contact.",
    "Scope. Ask what fails, when, who, changes, consistency, other apps, example users, workaround.",
    "Evidence. Pin the time window. Pull traffic, threat, URL, decryption, GlobalProtect, system, and config logs.",
    "Isolate. Compare failing vs working. What differs: rule, container, app, port, action?",
    "Reproduce. Ask the customer to retry while watching logs live.",
    "Prove. Policy match, tunnel status, IKE/IPsec SA checks, branch firewall logs.",
    "Fix with approval. Smallest change, show the diff, get written approval, push, track the job.",
    "Verify. Re-run the failing test. Ask the customer to confirm.",
    "RCA and close. Root cause, timeline, fix, prevention. Close only after confirmation.",
  ],
  writeupTitle: "Write-up and docs",
  writeupIntro: "Full documents ship with the final QA pass. In this build, the Brief holds the same content.",
  writeupLinks: [
    { label: "One page write-up", href: "#brief-writeup", note: "docs/WRITEUP.md" },
    { label: "Dev action items", href: "#brief-dev-items", note: "docs/DEV_ACTION_ITEMS.md" },
  ],
  writeupBodyTitle: "Features by priority",
  writeupFeatures: [
    "P0 Ticket workspace with the TAC playbook rail.",
    "P0 Scoping questions with live answers.",
    "P0 Time and user scoped evidence with pinning.",
    "P0 Compare failing vs working user.",
    "P1 Live reproduce and in-workspace console.",
    "P1 Fix with approval, push job, and verify gate.",
    "P1 Auto-drafted RCA from evidence.",
    "P2 Guide mode for new engineers.",
  ],
  devItemsTitle: "Dev action items",
  devItems: [
    "Log query service with time-partitioned index and PAN-OS query parser.",
    "Ticket to telemetry linking for users, devices, sites, and time windows.",
    "Read-only diagnostic sandbox for CLI and policy match.",
    "Config audit with structured before/after diffs per object.",
    "Change approval workflow with customer sign-off on the ticket.",
    "Live log streaming for reproduce sessions.",
    "Evidence model: immutable, timestamped, exportable, linked to RCA.",
    "Playbooks as data so new case types ship without code.",
  ],
  reviewTitle: "How to review",
  reviewSteps: [
    "Sign in as admin / 12345. Demo clock stays Tue 6 Oct 2026, 12:05 IST.",
    "Work TKT-24817 (Meet) and TKT-24823 (Pune) end to end from the playbook rail.",
    "Use Policies, Objects, Remote networks, Mobile users, Config audit, Logs, and Troubleshooting as evidence surfaces.",
    "Confirm cross-links: svc-quic-block to Block-QUIC, CHG-5120 to the rule, Pune to its logs.",
    "Reset demo from the user menu to re-run a case from Intake.",
  ],
  casesTitle: "Seeded cases",
  cases: [
    {
      id: "TKT-24817",
      title: "Google Meet not working for remote users",
      note: "CHG-5120 added Block-QUIC with svc-quic-block (UDP 443 and 19302-19309), which drops Meet media for mobile users.",
    },
    {
      id: "TKT-24823",
      title: "Pune branch offline, tunnel down",
      note: "CHG-4471 changed ipsec-prisma PFS DH group from group14 to group19. Phase 1 stays up. Phase 2 fails with NO_PROPOSAL_CHOSEN.",
    },
  ],
  creditsTitle: "Credits",
  credits: "Built by Sarthak Pant",
} as const;

export const supportingShared = {
  search: "Search",
  filters: "Filters",
  activeFilters: "Filters applied",
  demoClock: "Demo clock",
} as const;
