/** Copy for the Tickets queue. No em or en dashes. */

export const ticketsCopy = {
  pageTitle: "Tickets",
  pageSubtitle: "Active queue and closed history for Acme Corp.",
  tabActive: "Active",
  tabWaiting: "Waiting on customer",
  tabResolved: "Resolved",
  tabAll: "All",
  viewGrid: "Card grid",
  viewTable: "Table",
  emptyActive: "No active tickets in this view.",
  emptyWaiting: "No tickets waiting on the customer.",
  emptyResolved: "No resolved tickets yet.",
  emptyAll: "No tickets match this view.",
  openTicket: "Open",
  lastUpdate: "Updated",
  assignee: "Assignee",
  customer: "Customer",
  product: "Product",
  priority: "Priority",
  status: "Status",
  subject: "Subject",
  sla: "SLA",
  seededLabel: "tickets seeded",
  filtersApplied: "Filters applied",
  productMobile: "Mobile Users",
  productRemote: "Remote Networks",
  statusOpen: "open",
  statusInProgress: "in progress",
  statusPending: "pending customer",
  statusResolved: "resolved",
  statusClosed: "closed",
  slaMet: "met",
} as const;
