/** Copy for ticket workspace and playbook steps. No em or en dashes. */

export const workspaceCopy = {
  backToTickets: "Back to Tickets",
  notFoundTitle: "Ticket not found",
  notFoundBody:
    "That ticket id is not in the seeded queue. Return to tickets and open a card from the list.",
  readOnlyBanner: "Read-only history ticket. Thread and RCA are closed.",
  playbookTitle: "Playbook",
  stepDone: "Done",
  stepActive: "Active",
  stepLocked: "Locked",
  evidenceTitle: "Evidence",
  evidenceEmpty: "No pinned evidence yet. Pin items from Evidence in a later step.",
  replyPlaceholder: "Write a reply to the customer…",
  replyInternalPlaceholder: "Internal note (not visible to customer)…",
  replySend: "Send reply",
  replyNote: "Add internal note",
  replyModeCustomer: "Customer reply",
  replyModeInternal: "Internal note",
  templatesLabel: "Templates",
  templateAck: "Acknowledge",
  templateMoreInfo: "Need more detail",
  templateWorking: "Still investigating",
  typing: "Customer is typing…",
  intakeTitle: "Intake",
  intakeSummary: "Ticket summary",
  intakeAcknowledge: "Acknowledge and start",
  intakeAckHint: "Sends a first response and moves the case to Scope.",
  intakeAlready: "Intake complete. First response already sent.",
  intakeLinkedAlert: "Linked alert",
  intakeAffected: "Affected service",
  intakeNoAlert: "None",
  scopeTitle: "Scope",
  scopeAsk: "Ask customer",
  scopeAskAll: "Ask all at once",
  scopeAsked: "Asked",
  scopeAnswered: "Answered",
  scopeKeyFinding: "Mark as key finding",
  scopeKeyFindingOn: "Key finding",
  scopeSummaryTitle: "Scope summary",
  scopeWhat: "What",
  scopeWhen: "When",
  scopeWho: "Who",
  scopeChanges: "Changes",
  scopeExamples: "Example users",
  scopeEmptyField: "Not answered yet",
  scopeContinueHint: "Answer When and Who to unlock Evidence.",
  lockedPlaceholder: "This step is locked.",
  laterStep: "Full panel arrives in a later phase.",
  historyRcaTitle: "Root cause analysis",
  historySummary: "Summary",
  historyTimeline: "Timeline",
  historyRootCause: "Root cause",
  historyFix: "Fix",
  historyPrevention: "Prevention",
  statusLabel: "Status",
  customerLabel: "Customer",
  productLabel: "Product",
  slaLeft: "SLA",
  slaLeftSuffix: "left",
} as const;

export const PLAYBOOK_STEP_META: {
  id: import("@/types").PlaybookStep;
  number: number;
  label: string;
}[] = [
  { id: "intake", number: 1, label: "Intake" },
  { id: "scope", number: 2, label: "Scope" },
  { id: "evidence", number: 3, label: "Evidence" },
  { id: "isolate", number: 4, label: "Compare" },
  { id: "reproduce", number: 5, label: "Reproduce" },
  { id: "prove", number: 6, label: "Prove" },
  { id: "fix", number: 7, label: "Fix" },
  { id: "verify", number: 8, label: "Verify" },
  { id: "rca", number: 9, label: "RCA, close" },
];
